const MODULES=[
 {id:'meaning',name:'词义',short:'词义'},
 {id:'irregular_verb',name:'特殊变位',short:'特殊变位'},
 {id:'preposition_collocation',name:'固定搭配 / 介词搭配',short:'固定搭配'},
 {id:'synonym_near_synonym_antonym',name:'同义 / 近义 / 反义',short:'同反义'}
];
const INDEPENDENT={id:'same_root_prefix',name:'同根词辨析',short:'同根词辨析'};
const STORE='de-vocab-final-v4'; const USER_STORE_PREFIX='de-vocab-final-v4-user:';
let DB=null,state=blank(),ACTIVE_STORE=STORE,SB=null,AUTH_SESSION=null,cloudReady=false,cloudTimer=null,session=null;
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date();
function blank(){return {schema_version:8,history:[],unknown:[],modules:{},module_work:{},error_reports:{},settings:{}}}
function loadState(k=ACTIVE_STORE){try{return migrateState(JSON.parse(localStorage.getItem(k)||'null')||blank())}catch{return blank()}}
function migrateState(s){s={...blank(),...s};s.history=Array.isArray(s.history)?s.history:[];s.unknown=Array.isArray(s.unknown)?s.unknown:[];s.modules=s.modules||{};s.module_work=s.module_work||{};s.error_reports=s.error_reports||{};return s}
function save(){localStorage.setItem(ACTIVE_STORE,JSON.stringify(state)); if(cloudReady&&AUTH_SESSION){clearTimeout(cloudTimer);cloudTimer=setTimeout(saveCloud,250)}}
async function saveCloud(){if(!SB||!cloudReady||!AUTH_SESSION)return;try{await SB.from('user_state').upsert({user_id:AUTH_SESSION.user.id,state,updated_at:new Date().toISOString()},{onConflict:'user_id'})}catch(e){console.warn(e)}}
function uid(){return AUTH_SESSION?.user?.id||null}
function activate(uid){ACTIVE_STORE=USER_STORE_PREFIX+uid;state=loadState()}
function userStats(stage,m){const all=eligible(stage,m);const ids=new Set(all.map(x=>x.id));const h=state.history.filter(x=>Number(x.stage)===Number(stage)&&x.module===m&&ids.has(x.item_id));const passed=new Set((state.modules[`${stage}:${m}`]?.passedIds||[]));const corrected=new Set((state.modules[`${stage}:${m}`]?.correctedIds||[]));h.forEach(x=>{if(x.status==='corrected')corrected.add(x.item_id)});return {total:all.length,passed:[...passed].filter(x=>ids.has(x)).length,corrected:[...corrected].filter(x=>ids.has(x)).length,errors:h.length}}
function stageOfWord(w){return Number(w.stage_id||w.section_id)}
function wordMeaning(w){return w.meaning||''}
function normalize(s){return String(s||'').toLowerCase().replace(/[\s\u3000，,。.!！?？:：;；、“”"'‘’（）()\[\]{}\/\\]/g,'')}
function meaningCorrect(answer,std){const a=normalize(answer),b=normalize(std);if(!a)return false;if(a===b||a.includes(b)||b.includes(a))return true;const aa=[...a],bb=new Set([...b]);const hit=aa.filter(c=>bb.has(c)).length;return Math.min(hit/Math.max(aa.length,1),hit/Math.max([...bb].length,1))>=.55}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function byId(id){return DB.wordsById.get(Number(id))}
function eligible(stage,m){if(m==='meaning')return DB.words.filter(w=>stageOfWord(w)===Number(stage));if(m==='irregular_verb')return DB.words.filter(w=>stageOfWord(w)===Number(stage)&&DB.formsByWord.has(w.id));if(m==='preposition_collocation')return DB.collocs.filter(c=>c.form==='inline'&&Number(c.stage_id)===Number(stage)&&c.word_id!=null&&byId(c.word_id));if(m==='synonym_near_synonym_antonym')return DB.words.filter(w=>stageOfWord(w)===Number(stage)&&((relsFor(w).some(r=>r.in_db&&resolveWord(r.related_word)) )));return []}
function stageData(n){return DB.stages.find(s=>Number(s.id)===Number(n))}
function relsFor(w){return DB.relsByWord.get(w.id)||[]}
function resolveWord(text){const t=String(text||'').trim();const exact=DB.words.find(w=>normalize(w.word)===normalize(t));if(exact)return exact;const core=x=>normalize(String(x).replace(/^(der|die|das)\s+/i,'').replace(/[,，].*$/,''));const c=core(t);return DB.words.find(w=>core(w.word)===c)||null}
function meaningParts(s){return String(s||'').split(/[；;，,、\/]/).map(x=>normalize(x)).filter(x=>x.length>=2)}
function meaningRelatedWords(w){const parts=meaningParts(wordMeaning(w));if(!parts.length)return [];return DB.words.filter(x=>x.id!==w.id&&meaningParts(wordMeaning(x)).some(p=>parts.includes(p)))}
function reverseRelationWords(w,types){const out=[];for(const r of DB.rels){if(!types.includes(r.relation_type)||!r.in_db)continue;const rw=resolveWord(r.word),rr=resolveWord(r.related_word);if(rr?.id===w.id&&rw)out.push(rw)}return out}
function relationCorrect(w,typ){let direct=relsFor(w).filter(r=>(typ==='syn_near'?(r.relation_type==='synonym'||r.relation_type==='near_synonym'):r.relation_type===typ)&&r.in_db).map(r=>resolveWord(r.related_word)).filter(Boolean);if(typ==='syn_near')direct=[...direct,...meaningRelatedWords(w),...reverseRelationWords(w,['synonym','near_synonym'])];else direct=[...direct,...reverseRelationWords(w,['antonym'])];return direct.filter(Boolean).filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i)}
function relationDistractors(w,correct){const ids=new Set(correct.map(x=>x.id));const base=DB.words.filter(x=>x.id!==w.id&&!ids.has(x.id));const parts=meaningParts(wordMeaning(w));const score=x=>{const xp=meaningParts(wordMeaning(x));const overlap=xp.filter(p=>parts.includes(p)).length;const pos=(x.pos&&w.pos&&x.pos===w.pos)?1:0;return overlap*10+pos};return base.sort((a,b)=>score(b)-score(a)).slice(0,Math.max(0,10-correct.length))}
function rootGroups(){return DB.rootGroups}
function activeReport(stage,m){return state.error_reports[`${stage}:${m}`]||null}
function work(stage,m){return state.module_work[`${stage}:${m}`]||null}
function setWork(stage,m,w){state.module_work[`${stage}:${m}`]=w;save()}
function clearWork(stage,m){delete state.module_work[`${stage}:${m}`];save()}
function recordError(stage,m,w,user,standard,itemId=null){const t=now();const rec={id:crypto.randomUUID(),item_id:itemId??w.id,stage:Number(stage),module:m,word:w.word,time:t.toISOString(),user_answer:String(user??''),standard_answer:String(standard??''),status:'open'};state.history.push(rec);const k=`${stage}:${m}`;const mod=state.modules[k]||{};mod.correctedIds=mod.correctedIds||[];state.modules[k]=mod;return rec}
function markCorrect(stage,m,id){const k=`${stage}:${m}`;const mod=state.modules[k]||{};mod.passedIds=mod.passedIds||[];if(!mod.passedIds.includes(id))mod.passedIds.push(id);const hs=state.history.filter(h=>h.stage==stage&&h.module===m&&h.item_id===id);if(hs.length){const last=hs[hs.length-1];if(last.status==='open'){last.status='corrected';mod.correctedIds=mod.correctedIds||[];if(!mod.correctedIds.includes(id))mod.correctedIds.push(id)}}state.modules[k]=mod}
function makeReport(stage,m,errors,phase){const k=`${stage}:${m}`;state.error_reports[k]={id:crypto.randomUUID(),stage:Number(stage),module:m,created_at:now().toISOString(),phase,round:(work(stage,m)?.round||1),errors:errors.map(e=>({item_id:e.item_id,word:e.word,meaning:e.meaning,user_answer:e.user_answer,standard_answer:e.standard_answer,error_history_id:e.error_history_id})),awaiting_targeted:true};save();return state.error_reports[k]}
function clearReport(stage,m){delete state.error_reports[`${stage}:${m}`];save()}
function nav(active){return `<nav>${[['home','学习路径'],['root','同根词辨析'],['errors','错误本'],['review','长期复习']].map(x=>`<button class="nav ${active===x[0]?'active':''}" data-view="${x[0]}">${x[1]}${x[0]==='errors'?` <b>${state.history.length}</b>`:''}</button>`).join('')}</nav>`}
function accountNav(){const e=AUTH_SESSION?.user?.email||'';return `<div class="account"><span title="${esc(e)}">${esc(e||'当前账号')}</span><button id="logoutBtn">退出登录</button></div>`}
function layout(active,body){$('#app').innerHTML=`<header><div class="brand">德福考前必备-词汇 复习</div><div class="header-right">${nav(active)}${accountNav()}</div></header><main>${body}</main>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>b.dataset.view==='home'?renderHome():b.dataset.view==='root'?renderRootHome():b.dataset.view==='errors'?renderErrors():renderReview());$('#logoutBtn').onclick=logout}
function stageCard(s){const n=Number(s.id), mods=MODULES.map(m=>{const st=userStats(n,m.id),r=activeReport(n,m.id),w=work(n,m.id);return `<button class="node" data-stage="${n}" data-module="${m.id}"><span class="circle">${m.short[0]}</span><span class="node-text"><b>${m.name}</b><small>已过 ${st.passed} / ${st.total}　已改正 ${st.corrected}　累计错题 ${st.errors}</small>${r?'<em>有待查看的错误报告</em>':w?'<em>可继续练习</em>':''}</span></button>`}).join('');return `<article class="stage"><div class="stage-head"><div><span class="stage-no">PART ${n}</span><h2>第 ${n} 部分</h2></div><span class="pages">P${s.page_start}–${s.page_end}</span></div><div class="nodes">${mods}</div></article>`}
function renderHome(){layout('home',`<section class="hero"><div><div class="kicker">VOCABULARY REVIEW</div><h1>德福考前必备-词汇</h1><p>11 个部分全部开放；每部分四个编号模块。同根词辨析独立运行。</p></div><div class="stats"><div><strong>${DB.words.length}</strong><span>词库词条</span></div><div><strong>${state.history.length}</strong><span>历史错误</span></div><div><strong>${Object.keys(state.error_reports).length}</strong><span>待查看报告</span></div></div></section><section class="path">${DB.stages.map(stageCard).join('')}</section>`);document.querySelectorAll('.node').forEach(b=>b.onclick=()=>start(Number(b.dataset.stage),b.dataset.module))}
function reportItemWord(m,id){if(m==='preposition_collocation'){const c=DB.collocs.find(x=>Number(x.id)===Number(id));return c?(byId(c.word_id)||{word:c.word,meaning:c.gloss}):{}}return byId(id)||{}}
function reportHtml(stage,m){const r=activeReport(stage,m);if(!r)return `<div class="empty">当前没有待查看的错误报告。</div>`;return `<div class="error-summary"><div class="summary-card wide"><div class="kicker">CURRENT ROUND ERROR REPORT</div><h1>${esc(moduleName(m))} · 第 ${stage} 部分</h1><p class="muted">这份报告属于当前练习轮次。退出、刷新或重新打开后仍会保留，直到你明确开始下一轮针对性练习。</p><div class="error-table"><div class="error-head"><span>单词 / 项目</span><span>标准答案</span><span>你的答案</span></div>${r.errors.map(e=>`<div class="error-row"><span><b>${esc(e.word)}</b><small>${esc(wordMeaning(reportItemWord(m,e.item_id)))}</small></span><span>${esc(e.standard_answer)}</span><span>${esc(e.user_answer||'未作答')}</span></div>`).join('')}</div><button class="primary" id="targetBtn">针对性练习</button><button class="text-btn" id="backHome">先回学习路径</button></div></div>`}
function moduleName(m){return MODULES.find(x=>x.id===m)?.name||INDEPENDENT.name}
function showReport(stage,m){layout('home',reportHtml(stage,m));$('#targetBtn')?.addEventListener('click',()=>beginTarget(stage,m));$('#backHome')?.addEventListener('click',renderHome)}
function start(stage,m){if(activeReport(stage,m)){showReport(stage,m);return}const w=work(stage,m);if(w){const expected=eligible(stage,m);const ids=new Set(expected.map(x=>Number(x.id)));const valid=Array.isArray(w.ids)&&w.ids.length&&w.ids.some(id=>ids.has(Number(id)));if(valid){resume(stage,m,w);return}clearWork(stage,m)}const items=shuffle(eligible(stage,m));if(!items.length){showToast('这个部分没有可用题目。');return}setWork(stage,m,{stage,m,phase:'first',round:1,ids:items.map(x=>x.id),idx:0,errors:[]});session={stage,m,phase:'first',round:1,items,idx:0,errors:[]};renderPractice()}
function resume(stage,m,w){const items=m==='preposition_collocation'?w.ids.map(id=>DB.collocs.find(c=>Number(c.id)===Number(id))).filter(Boolean):w.ids.map(byId).filter(Boolean);if(!items.length){clearWork(stage,m);return start(stage,m)}session={stage,m,phase:w.phase||'first',round:Number(w.round||1),items,idx:Math.min(Number(w.idx||0),items.length),errors:Array.isArray(w.errors)?w.errors:[]};renderPractice()}
function beginTarget(stage,m){const r=activeReport(stage,m);if(!r)return;clearReport(stage,m);const items=m==='preposition_collocation'?r.errors.map(e=>DB.collocs.find(c=>Number(c.id)===Number(e.item_id))).filter(Boolean):r.errors.map(e=>byId(e.item_id)).filter(Boolean);const w={stage,m,phase:'targeted',round:(r.round||1)+1,ids:items.map(x=>x.id),idx:0,errors:[]};setWork(stage,m,w);session={stage,m,phase:'targeted',round:w.round,items,idx:0,errors:[]};renderPractice()}
function renderRootHome(){const groups=rootGroups();const done=new Set((state.modules.root_global?.doneGroups||[]));const pending=state.error_reports.root_global;layout('root',`<section class="page-title"><div class="kicker">INDEPENDENT MODULE</div><h1>同根词辨析</h1><p class="muted">不按 Part 划分，按词根组逐组进行。每个词条保留原来的 Part 与书页。</p></section>${pending?rootReportHtml(pending):`<div class="root-list">${groups.map((g,i)=>`<button class="root-card" data-root-index="${i}"><div><b>${esc(g.root)}</b><span>${esc(g.root_label||'')}</span></div><div><small>${g.member_count} 个词条</small><small>${g.parts.join(' / ')}</small><em>${done.has(g.group_id)?'已完成':'开始'}</em></div></button>`).join('')}</div>`}`);document.querySelectorAll('[data-root-index]').forEach(b=>b.onclick=()=>startRoot(Number(b.dataset.rootIndex)))}
function startRoot(index){const groups=rootGroups();const key='root_global';const r=state.error_reports[key];if(r){renderRootHome();return}const w=rootWork();if(w){resumeRoot(w);return}if(index<0||index>=groups.length)return;setRootWork({stage:0,m:INDEPENDENT.id,phase:'root',groupIdx:index,groupIds:groups.map(g=>g.group_id),errors:[]});session={stage:0,m:INDEPENDENT.id,groups,groupIdx:index,phase:'root',errors:[]};renderRootGroup()}
function resumeRoot(w){const groups=rootGroups();session={stage:0,m:INDEPENDENT.id,groups,groupIdx:Number(w.groupIdx||0),phase:w.phase||'root',errors:w.errors||[],targetIds:w.targetIds||[],targetIdx:Number(w.targetIdx||0),targetGroupIdx:Number(w.targetGroupIdx||w.groupIdx||0)};renderRootGroup()}
function rootGroup(){return session.groups[session.groupIdx]}
function rootMembers(g){return g.members||[]}
function rootWork(){return state.module_work.root_global||null}
function setRootWork(w){state.module_work.root_global=w;save()}
function clearRootWork(){delete state.module_work.root_global;save()}
function renderRootGroup(){if(session.phase==='root-target'){renderRootTarget();return}const g=rootGroup();if(!g){finishRoot();return}const rows=rootMembers(g).filter(m=>m.ex_de);layout('root',`<section class="practice"><div class="study-top"><span>同根词辨析</span><span>词根 ${session.groupIdx+1} / ${session.groups.length}</span></div><div class="question-card"><div class="kicker">${esc(g.root)}</div><h1>同根词</h1><div class="root-words">${rootMembers(g).map(m=>`<span>${esc(m.word)}<small>${esc(m.part)} · P${esc(m.page)}</small></span>`).join('')}</div><p class="muted">根据语境，把上面的词分别填入对应句子的空格。完成这一组后统一检查。</p>${rows.length?rows.map((m,i)=>`<div class="root-sentence"><div>${blankRootSentence(m)}</div><select data-root-answer="${i}"><option value="">请选择</option>${shuffle(rootMembers(g)).map(x=>`<option value="${esc(x.word)}">${esc(x.word)}</option>`).join('')}</select></div>`).join(''):'<div class="empty">这一组没有可用于匹配的例句，直接进入下一组。</div>'}<button class="primary" id="rootSubmit">${rows.length?'检查这一组':'下一组'}</button></div></section>`);$('#rootSubmit').onclick=rows.length?checkRootGroup:nextRootGroup}
function blankRootSentence(m){const re=new RegExp('('+m.word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','i');return esc(m.ex_de||'').replace(re,'<strong class="blank">_____</strong>')}
function checkRootGroup(){const g=rootGroup(),rows=rootMembers(g).filter(m=>m.ex_de),errors=[];rows.forEach((m,i)=>{const val=document.querySelector(`[data-root-answer="${i}"]`)?.value||'';if(normalize(val)!==normalize(m.word)){const rw=byId(m.word_id)||{id:m.word_id,word:m.word};const rs=stageOfWord(rw);const rec=recordError(rs,INDEPENDENT.id,rw,val,m.word);errors.push({item_id:m.word_id,word:m.word,meaning:m.meaning,user_answer:val,standard_answer:m.word,error_history_id:rec.id,group_id:g.group_id})}else {const rw=byId(m.word_id);markCorrect(rw?stageOfWord(rw):0,INDEPENDENT.id,m.word_id)}});if(errors.length){makeRootReport(errors,'root');showRootReport()}else nextRootGroup()}
function nextRootGroup(){const done=state.modules.root_global?.doneGroups||[];if(!done.includes(rootGroup().group_id))done.push(rootGroup().group_id);state.modules.root_global={...(state.modules.root_global||{}),doneGroups:done};session.groupIdx++;setRootWork({stage:0,m:INDEPENDENT.id,phase:'root',groupIdx:session.groupIdx,groupIds:session.groups.map(g=>g.group_id),errors:[]});save();if(session.groupIdx>=session.groups.length)finishRoot();else renderRootGroup()}
function finishRoot(){delete state.module_work.root_global;state.modules.root_global={...(state.modules.root_global||{}),last_pass_at:now().toISOString()};save();layout('root',`<section class="summary"><div class="summary-card"><div class="kicker">COMPLETE</div><h1>同根词辨析完成</h1><p>全部词根组已完成。</p><button class="primary" id="homeBtn">回到同根词辨析</button></div></section>`);$('#homeBtn').onclick=renderRootHome}
function makeRootReport(errors,phase){state.error_reports.root_global={id:crypto.randomUUID(),stage:0,module:INDEPENDENT.id,created_at:now().toISOString(),phase,group_id:errors[0]?.group_id||null,errors:errors.map(e=>({...e})) ,awaiting_targeted:true};save()}
function rootReportHtml(r){return `<div class="error-summary"><div class="summary-card wide"><div class="kicker">CURRENT ROUND ERROR REPORT</div><h1>同根词辨析 · 当前词根组</h1><p class="muted">这份报告独立于 Part；只记录当前这一轮新产生的错误。</p><div class="error-table"><div class="error-head"><span>词</span><span>标准答案</span><span>你的答案</span></div>${r.errors.map(e=>`<div class="error-row"><span><b>${esc(e.word)}</b><small>${esc(e.meaning||'')}</small></span><span>${esc(e.standard_answer)}</span><span>${esc(e.user_answer||'未作答')}</span></div>`).join('')}</div><button class="primary" id="rootTarget">针对性练习</button><button class="text-btn" id="rootHome">先回同根词辨析</button></div></div>`}
function showRootReport(){const r=state.error_reports.root_global;layout('root',rootReportHtml(r));$('#rootTarget').onclick=beginRootTarget;$('#rootHome').onclick=renderRootHome}
function beginRootTarget(){const r=state.error_reports.root_global;if(!r)return;delete state.error_reports.root_global;const groups=rootGroups();const gi=Math.max(0,groups.findIndex(g=>g.group_id===r.group_id));session={stage:0,m:INDEPENDENT.id,groups,groupIdx:gi,phase:'root-target',targetIds:r.errors.map(e=>e.item_id),targetIdx:0,errors:[],targetGroupIdx:gi};setRootWork({stage:0,m:INDEPENDENT.id,phase:'root-target',targetIds:session.targetIds,targetIdx:0,targetGroupIdx:gi});save();renderRootTarget()}
function renderRootTarget(){if(session.targetIdx>=session.targetIds.length){session.phase='root';session.groupIdx=session.targetGroupIdx;setRootWork({stage:0,m:INDEPENDENT.id,phase:'root',groupIdx:session.groupIdx,groupIds:session.groups.map(g=>g.group_id),errors:[]});renderRootGroup();return}const w=byId(session.targetIds[session.targetIdx]);if(!w){session.targetIdx++;return renderRootTarget()}layout('root',`<section class="practice"><div class="study-top"><span>同根词针对性练习</span><span>${session.targetIdx+1} / ${session.targetIds.length}</span></div><div class="question-card"><div class="kicker">中文 → 德语</div><h1>${esc(wordMeaning(w))}</h1><p class="muted">写出对应的德语词。</p><div class="input-row"><input id="answer" autocomplete="off" placeholder="写德语"><button class="primary" id="submit">提交</button></div></div></section>`);$('#submit').onclick=()=>rootTargetAnswer(w);$('#answer').onkeydown=e=>{if(e.key==='Enter')$('#submit').click()}}
function rootTargetAnswer(w){const a=$('#answer').value.trim();if(normalize(a)===normalize(w.word)){markCorrect(stageOfWord(w),INDEPENDENT.id,w.id)}else{const rec=recordError(stageOfWord(w),INDEPENDENT.id,w,a,w.word);session.errors.push({item_id:w.id,word:w.word,meaning:wordMeaning(w),user_answer:a,standard_answer:w.word,error_history_id:rec.id,group_id:session.groups[session.targetGroupIdx]?.group_id})}session.targetIdx++;setRootWork({stage:0,m:INDEPENDENT.id,phase:'root-target',targetIds:session.targetIds,targetIdx:session.targetIdx,targetGroupIdx:session.targetGroupIdx,errors:session.errors});if(session.targetIdx>=session.targetIds.length){if(session.errors.length){makeRootReport(session.errors,'root-target');clearRootWork();showRootReport()}else{session.phase='root';session.groupIdx=session.targetGroupIdx;setRootWork({stage:0,m:INDEPENDENT.id,phase:'root',groupIdx:session.groupIdx,groupIds:session.groups.map(g=>g.group_id),errors:[]});renderRootGroup()}}else{renderRootTarget()}}
function renderPractice(){const s=session,item=s.items[s.idx];session.relationType=null;if(!item){finishPractice();return}const w=s.m==='preposition_collocation'?(byId(item.word_id)||item):item;const total=s.items.length;let body='';if(s.m==='meaning'){body=meaningQ(w)}else if(s.m==='irregular_verb')body=verbQ(w);else if(s.m==='preposition_collocation')body=collocQ(item);else body=relationQ(w);layout('home',`<section class="practice"><div class="study-top"><span>${esc(moduleName(s.m))} · 第 ${s.stage} 部分</span><span>${s.idx+1} / ${total}</span></div>${body}</section>`);bindPractice()}
function meaningQ(w){if(session.phase==='first'||session.phase==='full'){return `<div class="question-card"><div class="kicker">德语 → 中文</div><h1>${esc(w.word)}</h1><p class="muted">先判断是否认识；认识后再写中文意思。</p><div class="eval-buttons"><button id="know">认识</button><button id="dontknow">不认识</button></div><div id="answerArea"></div></div>`}return `<div class="question-card"><div class="kicker">中文 → 德语</div><h1>${esc(wordMeaning(w))}</h1><p class="muted">写出对应的德语词。</p><div class="input-row"><input id="answer" autocomplete="off" placeholder="写德语"><button class="primary" id="submit">提交</button></div></div>`}
function verbQ(w){const f=DB.formsByWord.get(w.id);return `<div class="question-card"><div class="kicker">${session.phase==='targeted'?'针对性变位':'主动变位'}</div><h1>${esc(w.word)}</h1><div class="form-grid"><label>Präteritum<input id="praet" placeholder="写过去时"></label><label>Partizip II<input id="part" placeholder="写第二分词"></label></div><button class="primary" id="submit">提交</button></div>`}
function collocQ(item){const c=item;const w=byId(c.word_id)||{};const phrase=String(c.phrase||c.word||w.word||'');const prep=String(c.prep||'').trim();const caseMark=String(c.case_mark||'').trim();let display=phrase;const caseRe=caseMark?new RegExp('\\s*[+]?'+caseMark.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\.?(?=\\s|$)','i'):null;if(caseRe)display=display.replace(caseRe,'');if(prep){const re=new RegExp('(^|\\s)'+prep.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=\\s|$)','i');display=display.replace(re,'$1___')}display=display.replace(/\s{2,}/g,' ').trim();if(caseMark)display+=' ___';return `<div class="question-card"><div class="kicker">固定搭配 / 介词搭配</div><h1>${esc(c.gloss||wordMeaning(w))}</h1><div class="phrase">${esc(display)}</div><p class="muted">补出两个空：介词和格。题目不预先显示 A./D./G./N.。</p><div class="form-grid"><label>介词<input id="prepAnswer" placeholder="填写介词"></label><label>格<input id="caseAnswer" placeholder="填写格，如 D."></label></div><button class="primary" id="submit">提交</button></div>`}
function relationQ(w){const rs=relsFor(w);const types=[...new Set(rs.map(r=>r.relation_type==='antonym'?'antonym':'syn_near'))];if(meaningRelatedWords(w).length&&!types.includes('syn_near'))types.push('syn_near');const types2=types.filter(t=>relationCorrect(w,t).length);if(!types2.length)return `<div class="question-card"><h1>${esc(w.word)}</h1><p>没有可用于选择题的有效关系。</p><button class="primary" id="skip">下一题</button></div>`;const typ=session.relationType||types2[0];session.relationType=typ;const correct=relationCorrect(w,typ);const pool=relationDistractors(w,correct);const opts=shuffle([...correct,...pool]);return `<div class="question-card"><div class="kicker">${typ==='antonym'?'反义词':'同义 / 近义词'}</div><h1>${esc(typ==='antonym'?w.word:wordMeaning(w))}</h1><p class="muted">${typ==='antonym'?'请选择它的反义词。':'请选择所有与该中文意思相同或接近的词；正确答案可能不止一个。'}</p><div class="option-grid">${opts.map(o=>`<label><input type="${typ==='antonym'?'radio':'checkbox'}" name="rel" value="${o.id}"><span>${esc(o.word)}</span></label>`).join('')}</div><button class="primary" id="submit">提交</button></div>`}
function bindPractice(){const s=session,item=s.items[s.idx],w=s.m==='preposition_collocation'?(byId(item?.word_id)||item):item;$('#know')?.addEventListener('click',()=>showMeaningInput(w));$('#dontknow')?.addEventListener('click',()=>answerMeaning(w,'','不认识'));$('#submit')?.addEventListener('click',()=>submitGeneric(s.m==='preposition_collocation'?item:w));$('#skip')?.addEventListener('click',()=>{s.idx++;saveProgress();renderPractice()});$('#answer')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#submit')?.click()});$('#prepAnswer')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#submit')?.click()});$('#caseAnswer')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#submit')?.click()})}
function showMeaningInput(w){$('#answerArea').innerHTML=`<div class="input-row"><input id="answer" placeholder="写中文意思"><button class="primary" id="submitMeaning">提交</button></div><div id="meaningEvaluation"></div>`;$('#submitMeaning').onclick=()=>answerMeaning(w,$('#answer').value.trim(),$('#answer').value.trim());$('#answer').focus()}
function answerMeaning(w,a,u){if(!a){showToast('请先填写中文意思。');return}const box=$('#meaningEvaluation');if(!box)return;box.innerHTML=`<div class="meaning-score"><p class="muted">请根据你的实际答案与原书释义的对应程度自行判断：</p><div class="score-grid"><button data-score="10">10 分 · 完全对应</button><button data-score="7">7 分 · 基本正确</button><button data-score="3">3 分 · 只对一部分</button><button data-score="0">0 分 · 完全错误</button></div><div class="standard"><b>原书释义</b><br>${esc(wordMeaning(w))}</div></div>`;box.querySelectorAll('[data-score]').forEach(btn=>btn.onclick=()=>{const score=Number(btn.dataset.score);const ok=score>=7;handleResult(w,ok,a,wordMeaning(w),null,score)})}
function submitGeneric(w){if(session.m==='irregular_verb'){const f=DB.formsByWord.get(w.id);const a=`Präteritum: ${$('#praet').value.trim()}；Partizip II: ${$('#part').value.trim()}`;const ok=normalize($('#praet').value)===normalize(f.praeteritum)&&normalize($('#part').value)===normalize(f.partizip_ii);handleResult(w,ok,a,`Präteritum: ${f.praeteritum}；Partizip II: ${f.partizip_ii}`)}else if(session.m==='preposition_collocation'){const c=w;const word=byId(c.word_id)||{id:c.word_id,word:c.word};const pa=$('#prepAnswer')?.value.trim()||'';const ca=$('#caseAnswer')?.value.trim()||'';const ok=normalize(pa)===normalize(c.prep)&&normalize(ca)===normalize(c.case_mark);handleResult(word,ok,`介词：${pa||'未作答'}；格：${ca||'未作答'}`,`介词：${c.prep}；格：${c.case_mark}`,c.id)}else{const typ=session.relationType||'syn_near';const correct=relationCorrect(w,typ).map(x=>x.id);const selected=[...document.querySelectorAll('input[name="rel"]:checked')].map(x=>Number(x.value));const ok=selected.length===correct.length&&selected.every(x=>correct.includes(x));const ua=selected.map(x=>byId(x)?.word).join('、');handleResult(w,ok,ua,correct.map(x=>byId(x)?.word).join('、'))}}
function handleResult(w,ok,user,standard,itemId=null,score=null){const id=itemId??w.id;if(ok){markCorrect(session.stage,session.m,id);session.idx++;saveProgress();if(session.idx>=session.items.length)finishPractice();else showFeedback(w,true,user,standard,()=>renderPractice(),score)}else{const rec=recordError(session.stage,session.m,w,user,standard,id);if(score!=null)rec.score=score;session.errors.push({item_id:id,word:w.word,meaning:wordMeaning(w),user_answer:user,standard_answer:standard,error_history_id:rec.id,score});session.idx++;saveProgress();showFeedback(w,false,user,standard,()=>session.idx>=session.items.length?finishPractice():renderPractice(),score)}}
function showFeedback(w,ok,user,standard,next,score=null){const wrap=document.querySelector('.question-card');if(!wrap)return;wrap.innerHTML=`<div class="feedback ${ok?'feedback-ok':'feedback-wrong'}"><div class="feedback-mark">${ok?'✓':'×'}</div><div class="feedback-title">${ok?'正确':'错误'}${score!=null?` · ${score} 分`:''}</div><div class="feedback-your"><span>你的答案</span>${esc(user||'未作答')}</div><div class="feedback-answer"><span>标准答案</span><strong>${esc(standard)}</strong></div><button class="primary feedback-next" id="feedbackNext">下一题</button></div>`;$('#feedbackNext').onclick=next}
function saveProgress(){setWork(session.stage,session.m,{stage:session.stage,m:session.m,phase:session.phase,round:session.round,ids:session.items.map(x=>x.id),idx:session.idx,errors:session.errors})}
function finishPractice(){const s=session;const k=`${s.stage}:${s.m}`;if(s.errors.length){makeReport(s.stage,s.m,s.errors,s.phase);delete state.module_work[k];save();showReport(s.stage,s.m);return}if(s.phase==='targeted'){const items=shuffle(eligible(s.stage,s.m));session={stage:s.stage,m:s.m,phase:'full',round:s.round+1,items,idx:0,errors:[]};setWork(s.stage,s.m,{stage:s.stage,m:s.m,phase:'full',round:s.round+1,ids:items.map(x=>x.id),idx:0,errors:[]});renderPractice();return}clearWork(s.stage,s.m);const mod=state.modules[k]||{};mod.last_pass_at=now().toISOString();state.modules[k]=mod;save();layout('home',`<section class="summary"><div class="summary-card"><div class="kicker">PASS</div><h1>${esc(moduleName(s.m))} · 第 ${s.stage} 部分完成</h1><p>本轮全部正确。</p><button class="primary" id="homeBtn">回到学习路径</button></div></section>`);$('#homeBtn').onclick=renderHome}
function renderErrors(){const byStage={};state.history.forEach(h=>(byStage[h.stage]??=[]).push(h));layout('errors',`<section class="page-title"><div class="kicker">PERMANENT ERROR NOTEBOOK</div><h1>错误本</h1><p>按 11 个部分永久保存全部历史错误；每条记录保留准确时间、你的答案、标准答案和状态。</p></section>${DB.stages.map(s=>{const rows=byStage[s.id]||[];return `<details class="error-section" ${rows.length?'open':''}><summary>第 ${s.id} 部分 · P${s.page_start}–${s.page_end} · ${rows.length} 条历史错误</summary><div>${rows.length?rows.map(h=>`<article class="word-card"><div class="word-card-head"><h3>${esc(h.word)}</h3><span>${esc(moduleName(h.module))}</span></div><div class="metadata"><span>书页 ${byId(h.item_id)?.book_page??'—'}</span><span>${new Date(h.time).toLocaleString('zh-CN')}</span><span>${h.status==='corrected'?'已改正':'待强化'}</span></div><div class="history-list"><div class="history-item"><em>你的答案</em><span>${esc(h.user_answer||'未作答')}</span><em>标准答案</em><span>${esc(h.standard_answer)}</span></div></div></article>`).join(''):'<div class="empty">暂无历史错误。</div>'}</div></details>`}).join('')}`)}
function renderReview(){const ids=[...new Set(state.history.map(h=>h.item_id))].map(Number).map(byId).filter(Boolean);layout('review',`<section class="review-hero"><div class="kicker">LONG-TERM REVIEW</div><h1>${ids.length} 个历史错误项目</h1><p>长期复习独立于各部分和各模块，优先复习历史出错项目。</p>${ids.length?'<button class="primary" id="reviewStart">开始复习</button>':'<div class="empty">完成练习后，这里会形成全局复习池。</div>'}</section>`);$('#reviewStart')?.addEventListener('click',()=>{const items=shuffle(ids);session={stage:0,m:'meaning',phase:'review',round:1,items,idx:0,errors:[]};renderPractice()})}
function showToast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2500)}
function authShell(msg=''){if(!SB){$('#app').innerHTML=`<div class="auth-screen"><div class="auth-card"><h1>词库加载完成</h1><p>${esc(msg||'请配置 Supabase 后登录。')}</p></div></div>`;return}$('#app').innerHTML=`<div class="auth-screen"><div class="auth-card"><div class="kicker">DEUTSCH VOCAB</div><h1>登录你的学习账号</h1><div class="auth-tabs"><button class="auth-tab active" id="loginTab">登录</button><button class="auth-tab" id="signupTab">注册</button></div><div id="authFields"></div><button class="primary auth-submit" id="authSubmit">登录</button><div class="auth-message" id="authMessage">${esc(msg)}</div></div></div>`;let mode='login';const fields=()=>mode==='login'?`<label>邮箱</label><input id="email" type="email" autocomplete="email"><label>密码</label><input id="password" type="password" autocomplete="current-password"><button class="forgot-link" id="forgot">忘记密码？</button>`:`<label>邮箱</label><input id="email" type="email" autocomplete="email"><label>密码</label><input id="password" type="password" autocomplete="new-password"><label>确认密码</label><input id="confirm" type="password" autocomplete="new-password">`;const rf=()=>$('#authFields').innerHTML=fields();rf();const tab=m=>{mode=m;$('#loginTab').classList.toggle('active',m==='login');$('#signupTab').classList.toggle('active',m==='signup');$('#authSubmit').textContent=m==='login'?'登录':'注册';rf();$('#forgot')?.addEventListener('click',()=>forgot())};$('#loginTab').onclick=()=>tab('login');$('#signupTab').onclick=()=>tab('signup');$('#authSubmit').onclick=async()=>{const email=$('#email').value.trim(),p=$('#password').value;if(!email||p.length<6){$('#authMessage').textContent='请输入邮箱和至少 6 位密码。';return}if(mode==='signup'&&p!==$('#confirm').value){$('#authMessage').textContent='两次密码不一致。';return}$('#authSubmit').disabled=true;try{const r=mode==='login'?await SB.auth.signInWithPassword({email,password:p}):await SB.auth.signUp({email,password:p});if(r.error)throw r.error;if(r.data.session)await afterLogin(r.data.session);else $('#authMessage').textContent='注册成功，请直接登录。'}catch(e){$('#authMessage').textContent=e.message||'操作失败。'}finally{$('#authSubmit').disabled=false}}}
function forgot(){const e=prompt('请输入注册邮箱');if(!e)return;SB.auth.resetPasswordForEmail(e,{redirectTo:location.href}).then(r=>showToast(r.error?r.error.message:'重置邮件已发送。'))}
async function afterLogin(s){AUTH_SESSION=s;activate(s.user.id);cloudReady=true;try{const r=await SB.from('user_state').select('state').eq('user_id',s.user.id).maybeSingle();if(r.data?.state)state=migrateState(r.data.state);else await saveCloud()}catch(e){console.warn(e)}renderHome()}
async function logout(){await SB?.auth.signOut();cloudReady=false;AUTH_SESSION=null;state=blank();authShell()}
async function loadData(){const base='';const names=['words','sections','stages','verb_forms','preposition_collocations','word_relations','module5_root_groups','module5_members','prefix_groups','prefix_group_members','root_groups','module5_cross_part_groups'];const vals=await Promise.all(names.map(n=>fetch(base+n+'.json').then(r=>{if(!r.ok)throw Error('无法加载 '+n+'.json');return r.json()})));const o={};names.forEach((n,i)=>o[n]=vals[i]);DB={words:o.words,stages:o.stages,sections:o.sections,forms:o.verb_forms,collocs:o.preposition_collocations,rels:o.word_relations,rootGroups:o.module5_root_groups};DB.wordsById=new Map(DB.words.map(x=>[Number(x.id),x]));DB.wordsByNorm=new Map(DB.words.map(x=>[normalize(x.word),x]));DB.formsByWord=new Map();o.verb_forms.forEach(x=>DB.formsByWord.set(Number(x.word_id),x));DB.collocByWord=new Map();o.preposition_collocations.forEach(x=>{if(!DB.collocByWord.has(Number(x.word_id)))DB.collocByWord.set(Number(x.word_id),x)});DB.relsByWord=new Map();o.word_relations.forEach(x=>{const k=Number(x.word_id);if(!DB.relsByWord.has(k))DB.relsByWord.set(k,[]);DB.relsByWord.get(k).push(x)});return DB}
async function boot(){try{await loadData()}catch(e){document.body.innerHTML='<div style="padding:40px;font:16px system-ui">词库加载失败：'+esc(e.message)+'</div>';return}if(!window.SUPABASE_CONFIG?.url||!window.SUPABASE_CONFIG?.publishableKey){authShell('词库已加载，但缺少 Supabase 配置。请保留你现有的 supabase-config.js。');return}try{SB=window.supabase.createClient(window.SUPABASE_CONFIG.url,window.SUPABASE_CONFIG.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:localStorage}});const {data}=await SB.auth.getSession();if(data.session)await afterLogin(data.session);else authShell();SB.auth.onAuthStateChange((event,s)=>{if(event==='SIGNED_OUT'){AUTH_SESSION=null;cloudReady=false;state=blank();authShell()}else if(event==='SIGNED_IN'&&s&&!AUTH_SESSION)afterLogin(s)})}catch(e){authShell(e.message)}}
boot();
